// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cafApi.Contexts;

#nullable disable

namespace cafApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251010233738_CafProdutos")]
    partial class CafProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("cafApi.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("cafApi.Models.Cor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoHex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ProdutosCorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutosCorId");

                    b.ToTable("Cor");
                });

            modelBuilder.Entity("cafApi.Models.Produtos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("ImagemHover")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemPrincipal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit(1)");

                    b.Property<bool>("IsSale")
                        .HasColumnType("bit(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PrecoOriginal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("cafApi.Models.ProdutosCor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProdutosId")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutosId");

                    b.ToTable("ProdutosCores");
                });

            modelBuilder.Entity("cafApi.Models.ProdutosCorImagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("ProdutosCorId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProdutosCorId");

                    b.ToTable("ProdutosCorImagens");
                });

            modelBuilder.Entity("cafApi.Models.Cor", b =>
                {
                    b.HasOne("cafApi.Models.ProdutosCor", null)
                        .WithMany("Cores")
                        .HasForeignKey("ProdutosCorId");
                });

            modelBuilder.Entity("cafApi.Models.Produtos", b =>
                {
                    b.HasOne("cafApi.Models.Categoria", "Categoria")
                        .WithMany("Oculos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("cafApi.Models.ProdutosCor", b =>
                {
                    b.HasOne("cafApi.Models.Produtos", "Produtos")
                        .WithMany("CoresDisponiveis")
                        .HasForeignKey("ProdutosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("cafApi.Models.ProdutosCorImagem", b =>
                {
                    b.HasOne("cafApi.Models.ProdutosCor", "ProdutosCor")
                        .WithMany("Imagens")
                        .HasForeignKey("ProdutosCorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutosCor");
                });

            modelBuilder.Entity("cafApi.Models.Categoria", b =>
                {
                    b.Navigation("Oculos");
                });

            modelBuilder.Entity("cafApi.Models.Produtos", b =>
                {
                    b.Navigation("CoresDisponiveis");
                });

            modelBuilder.Entity("cafApi.Models.ProdutosCor", b =>
                {
                    b.Navigation("Cores");

                    b.Navigation("Imagens");
                });
#pragma warning restore 612, 618
        }
    }
}
